src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $pseudo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/layout.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}
        {% endblock %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="freehtml5.co" />
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{{ asset('css/animate.css') }}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{{ asset('css/icomoon.css') }}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{{ asset('css/flexslider.css') }}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{{ asset('css/style.css') }}">

	<link rel="stylesheet" href="{{ asset('css/customStyle.css') }}">
{% endblock %}

{% block body %}
    <header>
        <nav class="fh5co-nav" role="navigation">
		<div class="container-wrap">
			<div class="top-menu">
				<div class="row">
					<div class="col-md-12 col-offset-0 text-center">
						<div id="fh5co-logo"><a href="{{ path ('home') }}">Bibe'Lau</a>
                                                
          <form action="{{ path ('listlivre') }}" method="get" class="form-inline">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Je cherche..." {% if search is defined %} value="{{ search }}" {% endif %}>
             
              <div class="input-group-btn">
                  <button type="submit" class="btn btn-info"><span class="fa fa-search"></span>
                      Chercher
                      </button>
              </div>
            </div>
          </form>
		{% block button %}
			{% if app.user.username is defined %}
				<a href="{{ path ('app_logout')}}" ><input class="styled2" type="button" value="Se déconnecter"></a>
				<a href="{{ path ('user', {'id': app.user.id})}}" ><input class="styled" type="button" value="Mon profil"></a>
			{% else %}
				<a href="{{ path ('app_login') }}"> <input class="styled2" type="button" value="Se connecter"> </a>
				<a href="{{ path ('app_register') }}"> <input class="styled" type="button" value="S'inscrire"> </a>
			{% endif %}
		{% endblock %}
                                                   
                                                </div>
					</div>

				<div class="col-md-12 col-md-offset-0 text-center menu-1">
					<ul>
						<li><a href="{{ path ('home') }}">Home</a></li>
                     
						<li><a href="{{ path ('listCategory', {'category': 'science-fiction'}) }}">Science-Fiction</a></li>
						<li><a href="{{ path ('listCategory', {'category': 'guerre'}) }}">Guerre</a></li>
						<li><a href="{{ path ('listCategory', {'category': 'romance'}) }}">Romance</a></li>
						<li><a href="{{ path ('listCategory', {'category': 'classique'}) }}">Classique</a></li>
                                                {% if is_granted('ROLE_ADMIN') %}
                                                <a href="{{ path('article_index') }}">Menu Admin</a>
                                                {% endif %}
					</ul>
				</div>

				</div>
				
			</div>
		</div>
        </nav>
    

	{% block content %}{% endblock %}
	
    
    </header>
   
        
    </div>
    <div class="container-wrap">
        
		<footer id="fh5co-footer" role="contentinfo">
			
		</footer>
	</div>
{% endblock %}
{% block javascripts %}
    <script src={{ asset('js/jquery.min.js') }}></script>
	<!-- jQuery Easing -->
	<script src={{ asset('js/jquery.easing.1.3.js') }}></script>
	<!-- Bootstrap -->
	<script src={{ asset('js/bootstrap.min.js') }}></script>
	<!-- Waypoints -->
	<script src={{ asset('js/jquery.waypoints.min.js') }}></script>
	<!-- Flexslider -->
	<script src={{ asset('js/jquery.flexslider-min.js') }}></script>
	<!-- Carousel -->
	<script src={{ asset('js/owl.carousel.min.js') }}></script>
	<!-- Magnific Popup -->
	<script src={{ asset('js/jquery.magnific-popup.min.js') }}></script>
	<script src={{ asset('js/magnific-popup-options.js') }}></script>
	<!-- Counters -->
	<script src={{ asset('js/jquery.countTo.js') }}></script>
	<!-- Main -->
	<script src={{ asset('js/main.js') }}></script>
        <script src={{ asset('js/modernizr-2.6.2.min.js') }}></script>
{% endblock %}

templates/list.html.twig
{% extends '/layout.html.twig' %}

{% block content %}
<div class="container-wrap">
    <div class="well well-lg">
			<h2 class="media-heading">{{category}}</h2>
		</div>
	<div id="fh5co-counter" class="fh5co-counters">
		<div id="fh5co-services" class="fh5co-light-grey">
			<div class="row">
				{% for article in articles %}
				<div class="col-md-4 animate-box">      
					<div class="services">
						<a href={{ path('pagelivre', { 'id': article.id})}} class="img-holder"><img class="img-responsive" src="{{ asset(article.image) }}" alt="Free HTML5 Website Template by freehtml5.co"></a>
						<div class="desc">
							<h3><a href="#">{{ article.titre }}</a></h3>
							<p>{{ article.auteur }}</p>
						</div>
					</div>         
				</div>
				{% endfor %} 
            </div>
            <div class="row">
                {% if pages >= 2 %}
                <ul class="pagination">
                    {% if currentPage != 1 %} 
                    <li class="page-item"><a class="page-link" href="{{ path ("listCategoryPage", {"category": category, "page": currentPage - 1})}}">Précédent</a></li>
                    {% endif %}

                    {% for i in range(1, pages) %}
                    <li class="page-item"><a class="page-link" href="{{ path ("listCategoryPage", {"category": category, "page": i})}}">{{ i }}</a></li>
                    {% endfor %}

                    {% if currentPage != pages %}
                    <li class="page-item"><a class="page-link" href="{{ path ("listCategoryPage", {"category": category, "page": currentPage + 1})}}">Suivant</a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}